### PR TITLE
Add the ability to get workflow ID

### PR DESCRIPTION
**Pull request by mglaman**
I'd like to be able to compared the workflow ID in Commerce order to see if someone is still using default workflow.

### CODE REVIEW

**Comment by bojanz** [comment]
The idea was for people to use the base plugin method, $workflow->getPluginId(), but I guess that's not intuitive.

**Comment by mglaman** [comment]
Oh snap. I'll try that. It didn't show up in my autocomplete for available methods.

**Comment by mglaman** [comment]
@bojanz wel, also.. for the definition in Commerce Order is does have an "id" attribute. Wasn't sure if the idea was to allow an ID different than the plugin ID as well.

**Comment by bojanz** [comment]
Committed in be286db4b0ccd703c94e127d853be6165ca894b7, thanks.

**Pull request closed without merging**
