### PR TITLE
Add a test for StateItem

### PR DESCRIPTION
**Pull request by dawehner**

### CODE REVIEW

**Comment by bojanz** [comment]
Committed the config schema in 607438d810685cc8a740c3402a1b54ab67df6f2c so that you can focus on the test here :)

**Comment by dawehner** [comment]
Ah nice, yeah more to come

**Comment by dawehner** [comment]
Expanded the test coverage a bit

**Comment by bojanz** [comment]
Committed in 4fce22fbb85c03ebce4ae5ea22df17e33de8c46e
Travis enabled, build passed.
Thanks!

**Pull request closed without merging**
